### ISSUE TITLE
[Epic] Compare plugins

### ISSUE THREAD

**Issue by rfuzzo** [rfuzzo/tes3edit#14]
# basic compare plugins support

## short term:
- [x] modal window with all plugins in a folder, selectable
- [x] left panel overlay with a list of conflicts of selected plugins
- [x] main window overlay with a horizontal(?) list of conflicts for a record
- [x] get the load order right

##  long-term:
- [ ] single plugin compare
- [ ] editing conflicts (live? a patch?)

**Comment by rfuzzo** [comment]
- [ ] color-coded conflicts in editor
